apiVersion: apps/v1
kind: Deployment
metadata:
  name: reconciliation-service
  labels:
    app: reconciliation-service
    {{- include "pl.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reconciliation-service
  template:
    metadata:
      labels:
        app: reconciliation-service
    spec:
      containers:
        - name: reconciliation-service
          image: {{ include "pl.image" (dict "root" . "name" "reconciliation-service") }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8081
          env:
            - name: RECON_DB_URL
              value: "jdbc:postgresql://{{ .Values.postgres.host }}:5432/reconciliation"
            - name: RECON_DB_USER
              value: {{ .Values.postgres.user | quote }}
            - name: RECON_DB_PASSWORD
              valueFrom:
                secretKeyRef: { name: pl-secrets, key: postgres-password }
            - name: LEDGER_DB_URL
              value: "jdbc:postgresql://{{ .Values.postgres.host }}:5432/ledger"
            - name: LEDGER_DB_USER
              value: {{ .Values.postgres.user | quote }}
            - name: LEDGER_DB_PASSWORD
              valueFrom:
                secretKeyRef: { name: pl-secrets, key: postgres-password }
            - name: KAFKA_BOOTSTRAP
              value: "kafka:9092"
            - name: SERVER_PORT
              value: "8081"
            - name: SECURITY_ENABLED
              value: {{ .Values.security.enabled | quote }}
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef: { name: pl-secrets, key: jwt-secret }
            - name: MANAGEMENT_TRACING_SAMPLING_PROBABILITY
              value: {{ .Values.tracing.samplingProbability | quote }}
            - name: MANAGEMENT_OTLP_TRACING_ENDPOINT
              value: "http://jaeger:4318/v1/traces"
            - name: LOGGING_STRUCTURED_FORMAT_CONSOLE
              value: "ecs"
            - name: SPRING_APPLICATION_NAME
              value: "reconciliation-service"
            - name: SPRING_KAFKA_LISTENER_OBSERVATION_ENABLED
              value: "true"
          startupProbe:
            httpGet: { path: /actuator/health, port: 8081 }
            failureThreshold: 40
            periodSeconds: 5
          readinessProbe:
            httpGet: { path: /actuator/health, port: 8081 }
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /actuator/health, port: 8081 }
            initialDelaySeconds: 60
            periodSeconds: 20
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: reconciliation-service
  labels:
    {{- include "pl.labels" . | nindent 4 }}
spec:
  selector:
    app: reconciliation-service
  ports:
    - port: 8081
      targetPort: 8081
