apiVersion: v1
kind: Secret
metadata:
  name: pl-secrets
  labels:
    {{- include "pl.labels" . | nindent 4 }}
type: Opaque
stringData:
  jwt-secret: {{ .Values.security.jwtSecret | quote }}
  postgres-password: {{ .Values.postgres.password | quote }}
